Cron: 30 30 21 * * * #将在 每天的 5:30:30 开始登陆，并等待到6:00 开始Book，期间自己登陆图书馆预约系统会造成程序失效
Threads: 5 #每个账号开启5个并发线程
LogLevel: 1 #日志等级 暂时没啥用
User:
  - Username: "202111140022"
    Password: "qlu090034"
    BookList:
      - 8253
    InfoAPI:  
  - Username: "202111140009"
    Password: "qlu195225"
    BookList:
      - 8252
    InfoAPI:  
  - Username: "202111140006"
    Password: "qlu011930"
    BookList:
      - 8251
    InfoAPI:  
